### ISSUE TITLE
Tag a Release

### ISSUE THREAD

**Issue by haneefmubarak** [spotify/sparkey#38]
Hey @spkrka,

I know that you've not worked on this repo for a while and are working on a full Java version now, but I was wondering if you could tag a release at whatever latest point you feel is reasonable. I'd like to use this as a dependency for a project, but I'm hesitant (out of habit) to simply refer to HEAD or a specific commit hash.

Thanks!

**Comment by spkrka** [comment]
Sure, I've now made this tag:
https://github.com/spotify/sparkey/releases/tag/sparkey-1.0.0

Hope that helps1

**Comment by haneefmubarak** [comment]
Awesome. Thanks @spkrka!
